### ISSUE TITLE
Toc absolute links

### ISSUE THREAD

**Issue by MontrealSergiy** [neurohub/neurohub_documentation#11]
The documentation encourage users fork the wiki, so it could be good idea to replace the absolute links with relatives in the wiki toc. See example in my fork or https://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown

**Comment by bryancaron** [comment]
Resolved at least for the Table of Contents that had some broken links in the manual index portion of the main page.
