### ISSUE TITLE
The examples to mount squashfs don't run

### ISSUE THREAD

**Issue by maxadam2017** [neurohub/neurohub_documentation#13]
Re.: 5.2.Accessing Data 
squashfs images need to be mounted "read-only" explicitly
The examples should be edited to include `:ro` after each `--overlay <filename.squashfs>` directive.  For example:

```
singularity shell --overlay neurohub_ukbb_rfmri_ses2_0_bids.squashfs:ro --overlay neurohub_ukbb_rfmri_ses2_1_bids.squashfs:ro (etc.)
```
And:
```
cd /project/rpp-aevans-ab/neurohub/ukbb/
over=''
for ov in `printf "%s\n" "imaging/neurohub_ukbb_rfmri_ses2_?_bids.squashfs"`; do
	over+=" --overlay ${ov}:ro"
done
echo "${over}"
```
A comment should be inserted something like this:

> Note that a squashfs image is a read-only filesystem and so it is necessary to issue the `--overlay` mounting directive with the explicit `:ro` mount option following each squashfs file.

**Comment by bryancaron** [comment]
Confirmed with Pierre Rioux and Darcy Quesnel that for the latest version of singularity on Compute Canada that the :ro option is no longer required.  So the documentation has been updated on the documentation page so as to remove explicit inclusion of :ro from the syntax. 

Bryan.
