### ISSUE TITLE
Documentation Table of Contents listing and side-bar

### ISSUE THREAD

**Issue by bryancaron** [neurohub/neurohub_documentation#3]
The main page has a listing for the Table of Contents but that doesn't seem to match the list of topics or the order of the items in the side bar.  Can these be made consistent?

![Screen Shot 2020-09-11 at 12 31 53 PM](https://user-images.githubusercontent.com/65622686/92950701-19b0a700-f42b-11ea-9551-747208dbcd3a.png)

**Comment by VerenaSchuster** [comment]
Hi Bryan, I've noticed it already, the sidebar lists the pages in alphabetical order, but I will try to solve the problem.
