### ISSUE TITLE
missing items in Getting Started section

### ISSUE THREAD

**Issue by bryancaron** [neurohub/neurohub_documentation#4]
https://github.com/neurohub/neurohub_documentation/wiki/Getting-started
![Screen Shot 2020-09-11 at 12 36 07 PM](https://user-images.githubusercontent.com/65622686/92950843-6300f680-f42b-11ea-9de4-1d980c351c4f.png)

**Comment by VerenaSchuster** [comment]
This is just the headline, under which the options "get a neurohub accont" and "obtain a UKB account" are listed. But yes, it is kind of confusing.
