### ISSUE TITLE
Baseline JupyterHub Notebook information

### ISSUE THREAD

**Issue by bryancaron** [neurohub/neurohub_documentation#8]
Baseline starter JupyterHub documentation to be added.  This should include:

- what the basic purpose and capabilities are to work with the notebooks as part of NeuroHub
- pointer to the examples of notebooks in GitHub
- indication of where to connect to launch the JupyterHub notebooks (beluga, https://mcgill.syzygy.ca/, ...)

This is the documentation portion and not the notebooks themselves.

Location: https://github.com/neurohub/neurohub_documentation/wiki/2.4.Jupyter-Notebook

**Comment by bryancaron** [comment]
https://jupyterhub.beluga.calculquebec.ca/hub/login

**Comment by dlq** [comment]
The wiki has been updated with pointers to the Jupyter notebook examples.

Text will be included to talk about the rest of the points you raise.

**Comment by dlq** [comment]
Updated to include details about JupyterHubs available and a strong note about the technical nature of using the example.

**Comment by bryancaron** [comment]
closed.
