### ISSUE TITLE
Add info about the messaging system.

### ISSUE THREAD

**Issue by MontrealSergiy** [neurohub/neurohub_documentation#9]
Please add info regarding the messaging system. See a draft at https://github.com/MontrealSergiy/neurohub_documentation/wiki/

**Comment by MontrealSergiy** [comment]
![Untitled](https://user-images.githubusercontent.com/11949081/98107701-e148aa80-1e68-11eb-9161-6c472ff54523.png)
Here is relevant menu items and button in red.

**Comment by MontrealSergiy** [comment]
![image](https://user-images.githubusercontent.com/11949081/98130342-27613680-1e88-11eb-99a1-16b1a10d41e0.png)
@VerenaSchuster also see a Messaging blurb in Neurohub news

**Comment by VerenaSchuster** [comment]
thanks! I've added your screenshot and more  from the message within Neurohub news to information to 2.5.
